description: "Character Count Result"
evaluateOptions:
  maxConcurrency: 10
  showProgressBar: true
providers:
  - id: openai:chat:gpt-3.5-turbo
    label: GPT-3.5 Turbo
    config:
      temperature: 0.0
      response_format: { "type": "json_object" }
  - id: openai:chat:gpt-4o-mini
    label: GPT-4o Mini
    config:
      temperature: 0.0
      response_format: { "type": "json_object" }
  - id: openai:chat:gpt-4o
    label: GPT-4o
    config:
      temperature: 0.0
      response_format: { "type": "json_object" }
  - id: google:gemini-1.5-flash-002
    label: Gemini 1.5 Flash 002
    config:
      safetySettings:
        - category: HARM_CATEGORY_DANGEROUS_CONTENT
          threshold: BLOCK_ONLY_HIGH
      generationConfig:
        responseMimeType: application/json
        temperature: 0
        maxOutputTokens: 2048
  - id: google:gemini-1.5-flash-8b
    label: Gemini 1.5 Flash 8b
    config:
      generationConfig:
        response_mime_type: application/json
        temperature: 0
        maxOutputTokens: 2048
  - id: google:gemini-1.5-pro
    label: Gemini 1.5 Pro
    config:
      generationConfig:
        response_mime_type: application/json
        temperature: 0
        maxOutputTokens: 2048
  - id: google:gemini-2.0-flash-exp
    label: Gemini 2.0 Flash
    config:
      generationConfig:
        response_mime_type: application/json
        temperature: 0
        maxOutputTokens: 2048
  - id: google:gemini-exp-1206
    label: Gemini Exp 1206
    config:
      generationConfig:
        response_mime_type: application/json
        temperature: 0
        maxOutputTokens: 2048
  - id: google:gemini-2.0-flash-thinking-exp-1219
    label: Gemini 2.0 Flash Thinking
    config:
      generationConfig:
        temperature: 0
        maxOutputTokens: 2048
  - id: anthropic:messages:claude-3-5-haiku-20241022
    config:
      temperature: 0.0
  - id: anthropic:messages:claude-3-5-sonnet-20241022
    config:
      temperature: 0.0
  - id: openai:chat:deepseek-chat
    label: DeepSeek v3 Chat
    config:
      temperature: 0.0
      response_format: { "type": "json_object" }
      apiBaseUrl: https://api.deepseek.com/v1
      apiKeyEnvar: DEEPSEEK_API_KEY
  - id: groq:llama-3.3-70b-versatile
    label: Groq Llama 3.3 70b Versatile
    config:
      temperature: 0.0
  - id: xai:grok-beta
    config:
      temperature: 0.7
      apiKeyEnvar: XAI_API_KEY
defaultTest:
  assert:
    - type: contains-json
      value:
        {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "CharacterCountResult",
          "type": "object",
          "properties":
            {
              "count":
                {
                  "type": "number",
                  "description": "The number of occurrences of a given character in a word",
                },
            },
          "required": ["count"],
          "additionalProperties": true,
        }
  vars:
    system_instructions: file://system_instructions.xml

prompts: [prompt.json]
tests: test-*.yaml
